# Generated by Django 5.2.9 on 2025-12-31 07:55

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        TrigramExtension()
    ]
